# Basic Python

### 1. Split this string

In [7]:
s = "Hi there Sam!"

In [19]:
x=s.split()
print(x)


['Hi', 'there', 'Sam!']


### 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [14]:
planet = "Earth"
diameter = 12742

In [15]:
 print('The diameter of {} is {} kilometer.' .format(planet,diameter));

The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [16]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [18]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [3]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [25]:
array=np.zeros(10)
print(array)
array=np.ones(10)*5
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5,]

## 5. Create an array of all the even integers from 20 to 35

In [26]:
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)


Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
x=np.arange(0, 9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [28]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
arr=np.concatenate((a, b))
print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [30]:
import pandas as pd


In [31]:
data=[10,20,30,40,50,60]
df=pd.DataFrame(data)
print(df.iloc[:3])

    0
0  10
1  20
2  30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [37]:
from datetime import timedelta, date

def daterange(date1, date2):
  for n in range(int((date2 - date1).days)+1):
    yield date1+timedelta(n)

start_dt = date(2023, 1, 1)
end_dt = date(2023, 2, 10)
for dt in daterange(start_dt, end_dt):
  print(dt.strftime("%Y-%m-%d"))

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [38]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [40]:
 df = pd.DataFrame(lists, columns =['Num', 'Name', 'Age'])
 print(df)


   Num Name  Age
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
